### PR TITLE
add dc voter registration data post

### PR DESCRIPTION
**Pull request by ajschumacher**
@stvnrlly @mattbailey0 I pretty much just copied in from my blog. Feel free to edit for whatever you want.

### CODE REVIEW

**Comment by stvnrlly** [comment]
pinging @ajschumacher and @mattbailey0

**Comment by ajschumacher** [comment]
planning to work on this on the 14th~ feel free to adjust as needed without me though if you want!

**Comment by stvnrlly** [comment]
That plan sounds great.

**Comment by ajschumacher** [comment]
> The title's a little vague. Perhaps the first line of the post should be made into the title?

Good idea! Changed.

> Was that the only way to get the data? If so, make that clear.

I have "You can also get voter registration data on a per-ward basis in Microsoft Access or Excel formats. They will email it to you, but you have to fax in the form to make this request." (etc.) - I'll quote the whole "**Entire Voter Roll may only be obtained in Microsoft Access CD-ROM format.**" from the form too.

> How long did the process take you, and what were the hours that the office is open? This can provide a good contrast to the 24/7 availability of online data.

The process was going there (depends on your address) and then just a few minutes in the building; I didn't think it was worth mentioning. But I'll add the hours to the top, that'll fit okay there.

> What are some things that can be done with the data? That is, how does the average person benefit from greater accessibility here?

I don't think the average person benefits directly at all. People who want the data benefit if it's more easily available. People who want the data would want it for campaign purposes, most likely. Maybe research. I could imagine doing "get out the vote" efforts which would benefit the average person in that some average people would be encouraged to vote, maybe.

Hmm okay I'll add a little paragraph about what the data is and what could be done with it. This one:

"The data includes detailed information on registered DC voters including name, date registered, location in DC, and party, along with voting records (whether the person voted, not what their votes were) for the last forty or so elections. This could be used for planning voter registration drives or reminding people to vote, for example. It could also be combined with other data sets to get a more comprehensive understanding of DC, and probably lots of other things I haven't thought of."

> Are there any places that you know of that have done a good job in this area?

No. I think one of the states doesn't even _have_ voter registration at all.

> Could DC follow their example?

If they exist, then yes, probably.

> Is this the sort of thing that could just go up on data.dc.gov?

Yes. As I say though, "The clerk informed me that the data is updated daily." I don't know if data.dc.gov (or any common data dissemination platform right now, honestly) supports frequent data updates/synchronization.

> Regarding the :copyright:, it might be worth pointing out that you assumed public domain because DC did not provide any information about it.

I had "She told me there are no rules on how the data can be used. I take it to be public domain." I'll change it to "She told me there are no rules on how the data can be used. I take it to be public domain, because I haven't seen any other information on copyright or otherwise."

> Finally, my one textual edit: there should be a period at the very end.

Done.

**Comment by ajschumacher** [comment]
ugh it says there are merge conflicts

**Comment by ajschumacher** [comment]
okay fixed - you really went to town, eh?

**Comment by ajschumacher** [comment]
okay @stvnrlly I leave this in your capable hands! @mattbailey0 your hands are good too

**Comment by ajschumacher** [comment]
yeah maybe change the release date so it makes sense and is whatever you want the release date to be though?

**Comment by stvnrlly** [comment]
Looks good. I'd say let's move the break until after the first blockquote and set this to fire off on Tuesday (MLK Day is Monday).

**Comment by ajschumacher** [comment]
does that mean I should make those changes?

**Comment by stvnrlly** [comment]
Nope, don't worry about it: I was saying that for @mattbailey0 as the traditional post-puller.

**Comment by ajschumacher** [comment]
hooray for @mattbailey0!

**Comment by ajschumacher** [comment]
ooh is anything happening with this? @mattbailey0 @stvnrlly

**Comment by stvnrlly** [comment]
Good question. @mattbailey0, I'm happy to push this to the site if you'd like.

**Comment by mattbailey0** [comment]
Hey sorry - yes please do.

**Comment by mattbailey0** [comment]
And let me know - we'll twitter it up.

**Comment by stvnrlly** [comment]
In the words of Obi-Wan Kenobi, I will "Make it so".

**Comment by ajschumacher** [comment]
:sunglasses:

**Pull request merged**
