### PR TITLE
Correcting address of projects.js in gitraw

### PR DESCRIPTION
**Pull request by meiao**
I don't know if the branch master on files project was deleted and release stayed in its place.

But the projects.js was returning 404 from gitraw.com
I changed its address and the editor removed some whitespace.

I tried to test on my account, but since it adds the /codefordc-2.0 the site is not functional at
http://meiao.github.io/codefordc-2.0

### CODE REVIEW

**Comment by caseywatts** [comment]
I've independently deduced that the issue is from pointing to the non-existent `https://rawgit.com/codefordc/files/master/projects.js` instead of the much more existent `https://rawgit.com/codefordc/files/release/projects.js`.
:+1: to this PR

**Comment by stvnrlly** [comment]
Thanks, I missed PR this in my mad dash to figure out what was going on, but luckily we all found the same thing. The issue arose because I've been changing the default branch on repos from `master` to `release`, in part because it's a little more obvious when explaining the Git Flow concept. I haven't moved this repo over yet because (1) more people actually edit it and (2) I'm not sure if the default branch should be `release` or `develop` in cases where there's also a `gh-pages` branch.

While I'm talking about Git Flow: @meiao We don't edit `gh-pages` directly, so please submit future PRs against the `master` branch (or whatever replaces it).

**Comment by meiao** [comment]
I was going to send it to master, but I saw that gh-pages was over 100 commits ahead of it.
So I was in doubt and sent to gh-pages.

**Comment by stvnrlly** [comment]
Yeah, I think that's a function of each merge from `master` to `gh-pages` adding a commit. I can see how that would be confusing. It's mentioned in the README, but I wonder if there's a way for us to make that more clear.

**Pull request closed without merging**
